workspace:
  base: /test
  path: oel_page

services:
  web:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    environment:
      - DOCUMENT_ROOT=/test/oel_page
  mysql:
    image: registry.fpfis.eu/fpfis/sql:percona-5.7
    command: --innodb-log-file-size=1G --max_allowed_packet=1G --innodb-buffer-pool-size=512M --wait_timeout=3000 --net_write_timeout=3000 --log_error_verbosity=3
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    # Newer Selenium Chrome images are not supported at the moment by behat/mink-selenium2-driver.
    image: registry.fpfis.eu/fpfis/selenium:standalone-chrome-3.141.59-oxygen
    shm_size: 2g
    environment:
      - DISPLAY=:99
      - SE_OPTS=-debug
      - SCREEN_WIDTH=1280
      - SCREEN_HEIGHT=800
      - NODE_MAX_INSTANCES=5
      - NODE_MAX_SESSION=5

pipeline:
  composer-install:
    group: prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      - composer install --ansi --no-suggest --no-progress

  composer-update-lowest:
    group: post-prepare
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    volumes:
      - /cache:/cache
    commands:
      # @todo remove "composer install" step once the following issue is fixed.
      # @link https://webgate.ec.europa.eu/CITnet/jira/browse/OPENEUROPA-1234
      - composer update --prefer-lowest --prefer-stable --ansi --no-suggest --no-progress
    when:
      matrix:
        COMPOSER_BOUNDARY: lowest

  site-install:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/run drupal:site-install

  grumphp:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/grumphp run

  phpunit:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/phpunit

  behat:
    group: test
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/behat --strict

  debug:
    image: fpfis/httpd-php-ci:${PHP_VERSION}
    commands:
      - ./vendor/bin/drush ws --count 500
    when:
      status: failure

matrix:
  COMPOSER_BOUNDARY:
    - lowest
    - highest
  PHP_VERSION:
    - 7.3
